examine selected text: user.examine_selected_text_type()
test <user.ordinals>: print(ordinals)
test focus explorer: user.focus_explorer()
press tick: key(`)
test launch application <user.launch>: user.test_launch_application(launch)