print cheatsheet: user.cheatsheet()
update cheat sheet:
	# replace with "mac" or "linux" if needed
	user.cheatsheet("win")
	sleep(1.5)
	key(super)
	sleep(0.2)
	insert("Anaconda")
	sleep(0.25)
	key(enter)
	sleep(2.5)
	insert("cd %appdata%/Talon/user/kronenfeld/cheat sheet")
	key(enter)	
	insert("pandoc -s cheatsheet.md -c cheatsheet.css -f markdown-raw_html -t html -o cheatsheet.html")
	key(enter)
	sleep(2.5)
	user.add_links_to_cheatsheet()
	sleep(0.5)
	app.window_close()
show cheat sheet:
	key(super)
	sleep(0.2)
	insert("Anaconda")
	sleep(0.25)
	key(enter)
	sleep(4.5)
	insert("cd %appdata%/Talon/user/kronenfeld/cheat sheet")
	key("enter")
	sleep(0.5)
	insert("python -m http.server 8080")
	sleep(0.5)
	key("enter")
	key(super)
	sleep(0.2)
	insert("Edge")
	sleep(0.5)
	key("enter")
	sleep(0.3)
	insert("localhost:8080/cheatsheet.html")
	key("enter")